Repository PLREQ/PLREQ, pull requests merged in 2022-11, with the labels that each got.

#99 [Feat] #98 MatchView 에서의 수정 사항을 반영하고, 음악 매칭 관련 이슈를 해결하였습니다.
  PLREQ/PLREQ.xcodeproj/project.pbxproj
  PLREQ/PLREQ/Views/MatchView/MatchViewController.swift
Labels: bug, enhancement

#100 [Fix] #95 PlayListView가 viewDidAppear될 때 alert가 드는 버그 수정
  PLREQ/PLREQ/Views/PlayListView/PlayListViewController.swift
Labels: bug

#102 [Feat] #101 애플 뮤직 권한 수정
  PLREQ/PLREQ/ViewModels/PlayListDetailView/AppleMusicExport.swift
  PLREQ/PLREQ/Views/PlayListView/PlacePlayListView/PlacePlayListViewController.swift
  PLREQ/PLREQ/Views/PlayListView/PlayListViewController.swift
  PLREQ/PLREQ/Views/PlayListView/RecentPlayListView/RecentPlayListViewController.swift
Labels: enhancement

#109 [Fix] #89 기기별로 매칭된 음악 셀의 Gradient 가 다르게 적용되는 버그를 해결하였습니다.
  PLREQ/PLREQ/Extensions/UIImageView+.swift
  PLREQ/PLREQ/Views/MatchView/MatchViewController.swift
Labels: bug
